apiVersion: v1
kind: Service
metadata:
  name: be-test-app-service
  labels:
    run: be-test-app-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3333
  selector:
    app: be-test-app
