apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-client
  labels:
    app: profile-client
spec:
  replicas: 1
  template:
    metadata:
      name: profile-client
      labels:
        app: profile-client
    spec:
      containers:
        - name: profile-client
          image: europe-west1-docker.pkg.dev/nx-go-playground/nx-go-playground/profile-client:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: profile-client
