apiVersion: v1
kind: Service
metadata:
  name: profile-client-service
  labels:
    run: profile-client-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: profile-client
