apiVersion: v2
name: main-chart
description: A Helm chart for Kubernetess

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
dependencies:
  - name: cert-manager
    version: 0.7.8
    repository: https://charts.bitnami.com/bitnami
  - name: external-secrets
    version: 0.5.9
    repository: https://charts.external-secrets.io
  #  - name: vault
  #    version: 0.20.1
  #    repository: https://statcan.github.io/charts
  - name: consul
    version: 10.7.16
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    version: 17.0.10
    repository: https://charts.bitnami.com/bitnami
  - name: kube-prometheus
    version: 8.0.16
    repository: https://charts.bitnami.com/bitnami
    #  - name: prometheus
    #  - name: grafana
    #    repository: https://charts.bitnami.com/bitnami
    #    version: "16.13.1"
