apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    run: nginx-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
  #      targetPort: 3000
  selector:
    app: nginx
