apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #  - secrets.yaml
  - consul.yaml
  - grafana.yaml
  - redis.yaml
  - vault.yaml
commonLabels:
  tilt: "true"
#labels:
#  - pairs:
#      label: 1
#  - prometheus.yaml
#  - consul.yaml
#  - redis.yaml
#  - redis/templates/configmap.yaml
#  - redis/templates/secret.yaml
#  - grafana
#  - vault
#  - kube-prometheus
#  - ../base/../../apps/users/client/k8s/base
