apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: backend
build:
  artifacts:
  - image: go-guestbook-backend
    context: .
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/*.yaml
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
