apiVersion: v1
kind: Service
metadata:
  name: node-controller-service
  labels:
    run: node-controller-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: node-controller
