apiVersion: v1
kind: Service
metadata:
  name: profile-api-service
  labels:
    run: profile-api-service
spec:
  type: ClusterIP
  ports:
    - port: 3333
      protocol: TCP
      targetPort: 3333
  selector:
    app: profile-api
