resources:
  #  - configMap.yml
  - service.yml
  - deployment.yml
commonLabels:
  demo: profile-client-label
  service: users
#namespace: frontend

#  - servi
#namePrefix: demo
#nameSuffix: client
#images:
#  - name: busybox
#    newName: alpine
#    newTag: 3.6
configMapGenerator:
  - name: nginx-configs
    files:
      - nginx.conf
commonAnnotations:
  "consul.hashicorp.com/connect-inject": "true"
  "consul.hashicorp.com/connect-service": "users-client-test"
#  - name: haproxy-config
#    files:
#      - haproxy.cfg
#labels:
#  - pairs:
#      kubernetes.io/metadata.shit: aris
#      kubernetes.io/metadata.name: Aris
