resources:
  - configMap.yml
  - service.yml
  - deployment.yml

#namespace: users
#  - servi
#namePrefix: demo
#nameSuffix: client
#configMapGenerator:
#  - name: nginx-config
#    files:
#      - default.conf
