namePrefix: prod
commonLabels:
  variant: prod
commonAnnotations:
  note: I'm prod!
patchesStrategicMerge:
  - replica_count.yml
#
resources:
  - secrets.yml
  - deployment.yml

configMapGenerator:
  - name: config
    literals:
      - env=production
