apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #  - ../base/../../apps/test/be-test-app
  #  - ../base/../../dist/apps/functions/my-message
  #  - ../base/../../dist/apps/test/be-test-app
  #  - namespace.yaml
  #  - nginx
  #  - api
  - github.com/argoproj/argo-cd/manifests/crds
  - github.com/argoproj/argo-cd/manifests/base/application-controller
#  - github.com/argoproj/argo-cd/manifests/base/dex
#  - github.com/argoproj/argo-cd/manifests/base/repo-server
#  - github.com/argoproj/argo-cd/manifests/base/server
#  - github.com/argoproj/argo-cd/manifests/base/config
#  - github.com/argoproj/argo-cd/manifests/base/redis
#  - github.com/argoproj/argo-cd/manifests/cluster-rbac
#  - ingress.yaml

#namespace: argocd
#  - secrets.yml
#  - deployment.yml
#  - ../base
#  - servi

#namePrefix: demo
#nameSuffix: yuri
