apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #  - secrets.yaml
  - ../base/../../apps/users/client/k8s/base
  - ../base/../../apps/users/api/k8s/base
  #  - ../base/../../apps/test/be-test-app/k8s/base
  #  - ../base/../../apps/profile/client/k8s/base
  #  - ../base/../../apps/profile/api/k8s/base
  - ingress.yaml

#namespace: argocd
#  - secrets.yml
#  - deployment.yml
#  - ../base
#  - servi

#namePrefix: demo
#nameSuffix: yuri
