##apiVersion: v1
##kind: PersistentVolumeClaim
##metadata:
##  name: foo-pvc
##  namespace: foo
##spec:
##  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
##  volumeName: foo-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv1
  labels:
    failure-domain.beta.kubernetes.io/zone: us-central1-a__us-central1-b
spec:
  #  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  gcePersistentDisk:
    pdName: my-data-disk
    fsType: ext4
#  claimRef:
#    name: foo-pvc
#    namespace: storage
#---
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: gluster-vol-default
#provisioner: kubernetes.io/glusterfs
#parameters:
#  resturl: "http://192.168.10.100:8080"
#  restuser: ""
#  secretNamespace: ""
#  secretName: ""
#allowVolumeExpansion: true
