name: CI new nx
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout [main]
        with:
          fetch-depth: 0
#      - name: Nx Cloud - Main Job
#        uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.2
#        with:
#          node-version: "17"
#          parallel-commands: |
#            yarn nx workspace-lint
#            yarn nx format:check
#          parallel-commands-on-agents: |
#            yarn build
#            yarn lint
#            yarn test
  #        yarn nx affected --target=lint --parallel=3
  #        yarn nx affected --target=test --parallel=3 --ci --code-coverage
#        yarn nx affected --target=build --parallel=3

#  agents:
#    name: Nx Cloud - Agents
#    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.2
#    with:
#      number-of-agents: 3
#      node-version: "17"
