apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-controller
  #  namespace: users
  labels:
    app: main-controller
spec:
  replicas: 1
  template:
    metadata:
      name: main-controller
      labels:
        app: main-controller
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service": "main-controller"
        "consul.hashicorp.com/connect-service-protocol": "http"
        "consul.hashicorp.com/service-meta-version": "v.1.1"
        "prometheus.io/scrape": "true"
        "prometheus.io/port": "9102"
    spec:
      containers:
        - name: main-controller
          #          image: europe-west1-docker.pkg.dev/maya-mussia/nx-go-playground/users-api:latest
          image: yurikrupnik/main-controller:latest
          imagePullPolicy: IfNotPresent
          #          command: [ "node", "main.js" ]
          #            - node
          #            - main.js
          env:
            - name: MONGO_URI
              value: mongodb+srv://yurikrupnik:T4eXKj1RBI4VnszC@cluster0.rdmew.mongodb.net/
            #            - name: PROJECT_ID
            #              value: mussia14
            #            - name: FIREBASE_DATABASE_URL
            #              valueFrom:
            #                secretKeyRef:
            #                  key: firebase-database-url
            #                  name: firebase-secret
            #            - name: FIREBASE_PRIVATE_KEY
            #              valueFrom:
            #                secretKeyRef:
            #                  key: firebase-private-key
            #                  name: firebase-secret
            #            - name: FIREBASE_CLIENT_EMAIL
            #              valueFrom:
            #                secretKeyRef:
            #                  key: firebase-client-email
          #                  name: firebase-secret


      restartPolicy: Always
  selector:
    matchLabels:
      app: users-api
