apiVersion: v1
kind: Service
metadata:
  name: main-controller-service
  labels:
    run: main-controller-service
spec:
  type: ClusterIP
  ports:
    - port: 3008
      protocol: TCP
      targetPort: 8080
  selector:
    app: main-controller
